#!/bin/sh
xrandr --dpi 120 --output eDP1 --primary --mode 1920x1080 --pos 0x840 --rotate normal --output DP1-1 --mode 1920x1200 --pos 1920x216 --rotate normal --output DP1-2 --off
xrandr --dpi 120 --output eDP1 --primary --mode 1920x1080 --pos 0x840 --rotate normal --output DP1-1 --mode 1920x1200 --pos 1920x216 --rotate normal --output DP1-2 --mode 1920x1200 --pos 3840x0 --rotate left
