directory: /media/media/Music
library: /data/beets.db

plugins: lastgenre chroma fromfilename web duplicates replaygain scrub inline bpd convert edit mbsync

paths:
  default: '$albumartist/%if{$original_year,$original_year }$album%aunique{}/%if{$multidisc,Disc $disc/}%if{$track,$track }$artist - $album - $title'
  singleton: '$artist/%if{$original_year,$original_year }$artist - $title'
  comp: 'Compilations/$album%aunique{}/%if{$track,$track }$artist - $title'

import:
  languages: en
  timid: yes

item_fields:
  multidisc: 1 if disctotal > 1 else 0


acoustid:
  apikey: ITwDyyiq

replaygain:
  backend: gstreamer
  # overwrite: yes

web:
  host: 0.0.0.0

convert:
  never_convert_lossy_files: yes
  format: opus
  formats:
    opus:
      command: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
      extension: ogg
