directory: /media/media/Music
library: /media/media/Music/beets.db

plugins: lastgenre chroma fromfilename web duplicates replaygain smartplaylist scrub inline bpd convert edit

paths:
  default: '$albumartist/%if{$original_year,$original_year }$album%aunique{}/%if{$multidisc,Disc $disc/}%if{$track,$track }$artist - $album - $title'
  singleton: '$artist/%if{$original_year,$original_year }$artist - $title'
  comp: 'Compilations/$album%aunique{}/%if{$track,$track }$artist - $title'

import:
  languages: en

item_fields:
  multidisc: 1 if disctotal > 1 else 0

timid: yes

acoustid:
  apikey: ITwDyyiq

replaygain:
  backend: gstreamer
  # overwrite: yes

smartplaylist:
  playlist_dir: /media/media/Music/Playlists/
  playlists:
    - name: all.m3u
      query: ''

web:
  host: 0.0.0.0

convert:
  never_convert_lossy_files: yes
  format: opus
